- Dockerfile
> build(container): upgrade to ubi9/nodejs-22 images

- Dockerfile
- backend/package-lock.json
- backend/package.json
- backend/src/server.ts
- Reverts #12, which contains breaking changes that will require more attention to resolve.
- Sets the container build (which is also run in CI, hence the previous point wasn't caught) to compile the backend including type-checking.
- Cleans up some type-unsafe things in the backend server.
2. *...*
> chore(backend): type safety cleanup

- console-extensions.json
- package.json
- src/openshift/components/CryostatController.tsx
- src/openshift/pages/CreateRecordingPage.tsx
- src/openshift/pages/CreateRulesPage.tsx
- src/openshift/pages/CreateTargetPage.tsx
- src/openshift/pages/DashboardSoloPage.tsx
- start-console.sh
- webpack.config.ts
Related to: https://github.com/cryostatio/cryostat-web/pull/1534
This change adds a handful of missing pages from cryostat-web into the plugin. These would be the pages for creating targets, rules, and recordings, as well as the solo dashboard page.
I've also updated the `start-console.sh` script with a proxy so that requests for /api/v4 will hit the test/local cryostat.
This PR depends on basepath changes to cryostat-web in: https://github.com/cryostatio/cryostat-web/pull/1534. For the time being, I just have cryostat-web pointing to the current upstream commit because it at least has the react-router changes so these pages should …
> feat(pages): add pages for creating recordings, rules, and targets

- README.md
- backend/src/server.ts
Fixes up an import statement. Without this, since the recent linting cleanups, the backend fails to start because the transpiled `new k8s.KubeConfig()` results in an `undefined` dereference.
> fix(backend): correct kubernetes/client-node import

- .github/workflows/ci.yaml
> ci(push): fixup registry push only on push event

- .github/workflows/ci.yaml
- .github/workflows/push-ci.yaml
> ci(tags): do not use ref name as container tag in PRs

- .github/workflows/ci.yaml
- .github/workflows/push-ci.yaml
> ci(multiarch): build multiarch images for push

- backend/src/server.ts
- charts/openshift-console-plugin/templates/clusterrole.yaml
- src/openshift/pages/ExamplePage.tsx
- src/openshift/services/ApiService.tsx
Related to #3
Related to https://github.com/cryostatio/cryostat-operator/pull/1023
The console plugin UI now looks up ConsolePlugin CR instances in the cluster, specifically for one named `cryostat-plugin`, and uses this to determine the location of the plugin frontend proxy service. This is the cluster-managed service which points to the plugin backend, which is the Cryostat CR proxy that the plugin requests should be routed to.
This allows the UI to correctly locate the frontend proxy that it should send requests to, even if that proxy may not be running in the typical `plugin--cryostat-plugin` namespace. This may be the case when …
> feat(plugin): dynamic lookup of ConsolePlugin CR

- .github/workflows/ci.yaml
- .github/workflows/pr-ci.yaml
- Dockerfile
See https://github.com/cryostatio/cryostat/pull/786
Related to https://github.com/cryostatio/cryostat-operator/issues/611
Splits up the CI job for building containers, so that each arch (amd64 and arm64) for the multiarch manifest is built in parallel, and on a native-arch runner rather than cross-compiling using qemu.
Very significantly faster build. Sequentially building the two archs on an amd64 runner usually takes about an hour total, but this time is heavily dominated by the emulation slowdown of cross-compilation running under qemu. With this change each build takes a bit over 10 minutes, and since they are done in parallel, …
> ci(runner): split build across per-arch runners

- .github/workflows/ci.yaml
- backend/src/server.ts
- src/openshift/components/CryostatContainer.tsx
- src/openshift/components/CryostatController.tsx
- src/openshift/components/CryostatSelector.tsx
- src/openshift/services/PluginService.tsx
- webpack.config.ts
Adds a CryostatSelector component that updates the current page on selection of a Cryostat service.
It is a trimmed down version of the existing ExamplePage to only include the relevant parts required for selecting services. There is a state object to hold the service information that is passed into the CryostatSelector from the CryostatContainer, and is used as the key for the CryostatController. The idea here is that when the CryostatSelector has a new service picked it will update the state and cause a re-render of the CryostatController to update the page.
I've also updated the webpack config for production builds to set …
> feat(selector): extract CryostatSelector into its own component

- Dockerfile
- webpack.config.ts
Uses `yarn build` instead of `yarn build-dev` for the container build.
Previously, `yarn build` was resulting in errors due to the style attributes of some of the cryostat-web SVG classes. I noticed this only seemed to happen if my cryostat-web had installed its own dependencies. What looks to have happened is that the console plugin is ending up with csstype v3.1.3, which has a different type structure of text-align than the versions before it, and cryostat-web was pulling in v3.1.1.
v3.1.3 (https://github.com/frenic/csstype/blob/v3.1.3/index.d.ts#L20023)
`export type TextAlign = Globals | "-webkit-match-parent" | "center" | "end" …
> fix(Dockerfile): use yarn build instead of build-dev

- backend/package-lock.json
- backend/package.json
- backend/src/server.ts
- src/openshift/components/CryostatContainer.tsx
- src/openshift/services/PluginService.tsx
Depends on https://github.com/cryostatio/cryostat-web/pull/1544
Depends on https://github.com/cryostatio/cryostat-web/pull/1547
Combine with ~~#1544~~ cryostatio/cryostat-web#1547. This should allow the plugin to make all HTTP API requests. Previously, the lack of CSRF handling meant only GET requests would get through to the backend. Now, all requests like PATCH or POST should also get through. This fixes up GraphQL in particular, so the Archives view can be used to test that.
The plugin UI does strange de-selection of the Cryostat instance, so it can be annoying to navigate around. Separate bug to be tackled. Re-selecting the same …
> feat(proxy): websocket proxying, CSRF handling

- src/openshift/components/CryostatSelector.tsx
- src/openshift/services/PluginService.tsx
Related to #3
Adds a button on the context selector bar that allows for opening a new browser tab pointed at the Cryostat instance's Route. If there is no Route (located by looking in the same Service Namespace, for a Route with the same name as the Service) or if the URL from the Route cannot be determined, then the button is disabled.
(helm installed, with route)
(helm installed, no route)
(operator installed, with route)
Not all functionality is exposed through the plugin UI. For example, file uploads (rules as JSON, custom event templates, or JFR files for archives) do not work. This is because console plugins must go through …
> feat(selector): add button to open standalone Cryostat Web UI

- src/openshift/components/CryostatContainer.tsx
Related to #3
Hooks up a simplified graphical notification alert group for displaying toast-style notification popup boxes. Since there is no sidebar or pullout notification drawer there is no mechanism for hiding or marking notifications as read, and no "View more" overflow handling. There is some hacky processing of the notifications stream done to try to filter them by the least noisy types and to de-duplicate them (band-aid for still not perfected WebSocket/NotificationChannel handling). There is no way to review notifications after they time out.
These notifications are used to communicate to the user that actions have been …
> feat(notifications): rough implementation of notification toasts

- console-extensions.json
- package.json
The SettingsPage doesn't quite work at the moment, so this PR comments out it's usage in the `console-extensions.json` to be returned when this can be fixed up.
For the time being the console plugin will be like a "default" view of cryostat-web, and if users want to have more fine-grain control over the UI there is the option now to open the dedicated cryostat-web view for a namespace.
> chore(pages): remove SettingsPage navigation

- src/openshift/components/CryostatContainer.tsx
Depends on https://github.com/cryostatio/cryostat-web/pull/1554
2. *...*
> chore(service): lazy init

- backend/src/server.ts
- src/openshift/components/CryostatContainer.tsx
- src/openshift/components/CryostatSelector.tsx
Fixes: #110 
Depends on https://github.com/cryostatio/cryostat-web/pull/1557
- path handling cleanup in the backend
- use the queried Route to set a capability override for the Grafana dashboard URL. If no Route can be determined then hide the "View in Grafana" action item, since using the console infra proxy doesn't work (described in #110)
- some more general cleanup and refactoring. Notably, removed duplicate `<Provider>` redux components that were added the last time I tried splitting things up
2. *...*
> fix(grafana): enable "View in Grafana" if Route is available

- src/openshift/components/CryostatContainer.tsx
- src/openshift/components/CryostatController.tsx
- src/openshift/utils/utils.ts
Fixes: #118 
This change moves the navigation highlighting checks from the CryostatController to the CryostatContainer.
When the checks were originally put in place we didn't yet have the empty state, so I added these checks to occur just prior to the nested pages being rendered. Now that the repo has progressed a lot and there is an empty state that happens in CryostatContainer the checks have to be moved up to that component in order to apply at the same time as the empty states.
Makes the navigation highlight look as expected.
> fix(nav): move nav highlighting checks from controller to container

- src/openshift/styles/plugin.css
> fix(topology): override css for tab content view

- package.json
- src/openshift/pages/RecordingsPage.tsx
- src/openshift/pages/TopologyPage.tsx
- src/openshift/styles/plugin.css
- yarn.lock
Fixes: #[125](https://github.com/cryostatio/cryostat-openshift-console-plugin/issues/125)
Applies missing PF css to pages that make use of them. 
DescriptionList -> TopologyPage
Overflow-menu -> RecordingsPage
The console-dynamic-plugin-sdk documentation mentions to _avoid_ directly importing from '@patternfly/patternfly' [link](https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/upgrade-PatternFly.md#css-styling) but in this case we're missing stylesheets on a couple of pages.
Taking a look at the PF support [table](https://github.com/openshift/console/tree/master/frontend/packages/console-d …
> fix(css): apply missing stylesheets to Topology and Recordings

- .github/workflows/ci.yaml
- .github/workflows/push-ci.yaml
- **ci(tags): use package.json version as an image tag**
- **remove commit sha tag**
2. *...*
> ci(tags): use package.json version as an image tag

- package.json
- yarn.lock
This reverts commit d78daa3691c6b6991d12731eaece1b8822c01528.
2. *...*
> Revert "Bump webpack-cli from 4.10.0 to 6.0.1 (#25)"

- backend/src/server.ts
The Helm chart defaults to port 9443 for the plugin backend. The Operator also deploys the backend using 9443.
https://github.com/cryostatio/cryostat-openshift-console-plugin/blob/cefcb39d1d5dd7c835ab2ec34f4fa72d50a23b23/charts/openshift-console-plugin/values.yaml#L8
https://github.com/cryostatio/cryostat-openshift-console-plugin/blob/cefcb39d1d5dd7c835ab2ec34f4fa72d50a23b23/charts/openshift-console-plugin/templates/deployment.yaml#L28
https://github.com/cryostatio/cryostat-operator/blob/ebd66022e5317009636a70aa24c601ffb3a26952/config/openshift/console-plugin/deployment-cryostat-plugin.yaml#L37 …
> fix(backend): default port number in code agrees with config default

- backend/src/server.ts
Fixes: #173
Improves error handling so that upstream Cryostat connection failures are handled gracefully by the plugin proxy.
Prevents the plugin proxy from dying so easily (and being restarted by OpenShift, but maybe slowly with some backoff logic) if upstream Cryostat connections fail. This can happen when the upstream Cryostat is not yet ready to accept connections, for example.
2. *...*
> fix(proxy): handle upstream Cryostat connection failures

- .dockerignore
- backend/src/server.ts
See #237
See https://github.com/expressjs/express/issues/6038
2. *...*
> fix(express): adjustment for v5
