- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/dependabot.yml
- .github/labeler.yml
- .github/pull_request_template.md
- .github/release.yml
- .github/workflows/ci.yaml
- .github/workflows/pr-ci.yaml
- .github/workflows/push-ci.yaml
- OWNERS
Fixes #4
Example run: https://github.com/andrewazores/cryostat-openshift-console-plugin/actions/runs/12698304391
> ci(build): set up project CI

- .github/workflows/pr-ci.yaml
- .github/workflows/push-ci.yaml
> ci(queue): enable merge queue processing

- .gitignore
- README.md
- console-extensions.json
- locales/en/common.json
- package.json
- src/openshift/pages/ExamplePage.tsx
- start-console.sh
- webpack.config.ts
- yarn.lock
Fixes: [#40](https://github.com/cryostatio/cryostat-openshift-console-plugin/issues/40)
This change is the plugin-side counterpart to: https://github.com/cryostatio/cryostat-web/pull/1527
There are a couple of changes that make up this PR:
- the i18n namespace used must match the ConsolePlugin name as listed in package.json, which in our case is currently "cryostat-plugin", so the i18n namespace must be update everywhere to be "plugin__cryostat-plugin" in order to be picked up by the Console
- after the above changes, the Console now expects a single json called "plugin__cryostat-plugin.json". I have added a function to the webpack …
> chore(i18n): combine cryostat-web i18n strings into plugin__cryostat-plugin namespace

- .github/workflows/ci.yaml
- .github/workflows/push-ci.yaml
> ci(push): push to registry on merge

- .github/workflows/ci.yaml
> ci(push): add ref shortname to container tags

- .github/workflows/ci.yaml
> ci(push): fixup #61

- .github/workflows/ci.yaml
> ci(push): include commit hash in container tags

- .github/workflows/ci.yaml
- .github/workflows/push-ci.yaml
- **ci(push): refactor tags handling**
- **inherit secrets on push action**
See #58
2. *...*
> ci(push): refactor tags handling

- .github/workflows/ci.yaml
> ci(tags): include additional tags in push

- src/openshift/components/CryostatContainer.tsx
- src/openshift/pages/ExamplePage.tsx
- src/openshift/services/PluginContext.tsx
- src/openshift/services/PluginService.tsx
Related to #3
Depends on https://github.com/cryostatio/cryostat-web/pull/1542
2. *...*
> feat(context): override URL and headers for API requests

- src/openshift/components/CryostatContainer.tsx
- src/openshift/components/CryostatSelector.tsx
> fix(selector): correct state management to avoid deselection on navigation

- src/openshift/components/CryostatContainer.tsx
Fixes: https://github.com/cryostatio/cryostat-web/issues/1551
This change will require: https://github.com/cryostatio/cryostat-web/pull/1550
This PR adds the pluginContext into the ReportService so that it can be used for the Automated Analysis view.
Required to view the automated analysis reports.
> chore(context): pass the CryostatContext into the ReportService

- src/openshift/components/CryostatContainer.tsx
Depends on https://github.com/cryostatio/cryostat-web/pull/1553
See https://github.com/cryostatio/cryostat-openshift-console-plugin/pull/90
2. *...*
> feat(capabilities): disable UI file upload capability

- src/openshift/components/CryostatContainer.tsx
> fix(about): perform server query to populate data for About page

- .eslintrc.yml
- package.json
- src/openshift/components/CryostatContainer.tsx
- src/openshift/components/CryostatSelector.tsx
- src/openshift/pages/example.css
- yarn.lock
Related to #3
Related to #102
Just some refactoring to simplify the state management and relationship between the Container and Selector components, as well as add a loading state in case the Service k8s query takes some time to complete, and an error state in case that fails.
> chore(selector): refactor to simplify state management

- src/openshift/components/CryostatContainer.tsx
Fixes: #108
Applies stylesheets from cryostat-web onto the plugin at CryostatContainer.
This fixes 108, but does not fix 101.
Cryostat-web has stylesheets that are imported by the index.tsx, that aren't currently imported by the plugin. I've added them to the CryostatContainer which wraps all of the components, so the stylesheets should be applied.
Before:
(taken from issue 108)
After:
Local console:
CRC:
> chore(css): apply cryostat-web stylesheets to CryostatContainer

- charts/openshift-console-plugin/values.yaml
> chore(resources): set default resource requests/limits and replicas

- .mergify.yml
> chore(mergify): set up mergify

- backend/src/server.ts
Fixes: #116
- cleans up upstream path determination to remove some unnecessary logic now that the frontend is behaving better
- ensure query strings are preserved in the request passed upstream
Corrects proxy behaviour to send the upstream request without altering the semantics. In particular any request query string is properly re-appended to the updated upstream path, which fixes the immediate bug observed in #116.
1. Deploy plugin as usual
2. Create a Cryostat instance
3. Go to plugin UI, select instance
4. Create `localhost:0` custom target or otherwise deploy a target application
5. Go to plugin Automated Rules
6. Create a rule …
> fix(proxy): clean up proxy path handling and ensure querystrings are preserved

- backend/package.json
- package.json
> chore(version): set version to 4.0.0-dev

- .gitmodules
> chore(modules): cryostat-web tracks main

- .gitmodules
> chore(modules): cryostat-web tracks release branch
